<?php


namespace Formy\Tests;


use Formy\Providers\FormyServiceProvider;
use Formy\Tests\Classes\SimpleObject;
use Formy\Tests\Forms\EntryFormWithSaveOnHandle;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Orchestra\Testbench\TestCase;
use Formy\Tests\Forms\EntryForm;

class SimpleFormsTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->withFactories(__DIR__ . '/database/factories');
    }

    protected function getEnvironmentSetUp($app)
    {
        parent::getEnvironmentSetUp($app); // TODO: Change the autogenerated stub
        $app['config']->set('database.default', 'testing');
        $app['config']->set('database.connections.testing', [
            'driver' => 'sqlite',
            'database' => ':memory:'
        ]);

        include_once __DIR__ . '/database/migrations/create_posts_table.php';

        (new \CreatePostsTable())->up();
    }


    protected function getPackageProviders($app)
    {
        return [ FormyServiceProvider::class ];
    }

    /**
     * @test
     * @dataProvider provider
     */
    public function canCreateAndHandleSimpleFormWithArrayData($request, $needed)
    {
        $form = EntryForm::create([]);
        $updated = $form->handle($request);

        $this->assertEquals([ 'title' => $needed ], $updated);
    }

    /**
     * @test
     * @dataProvider provider
     */
    public function canCreateAndHandleSimpleFormWithObjectData($request, $needed)
    {
        $newObject = new SimpleObject();
        $form = EntryForm::create($newObject);
        $updated = $form->handle($request);

        $neededObject = new SimpleObject($needed);

        $this->assertEquals($neededObject, $updated);
    }

    /**
     * @test
     * @dataProvider provider
     */
    public function canCreateAndHandleSimpleFormWithDefaultData($request, $needed)
    {
        $form = EntryFormWithSaveOnHandle::create();
        $updated = $form->handle($request);

        $neededValue = new SimpleObject($needed);
        $this->assertEquals($neededValue, $updated);
    }

    /** @test */
    public function isDatabaseCreated()
    {
        $post = new \Formy\Tests\Post();
        $post->title = 'Hello world!';
        $post->save();

        $loadedPost = \Formy\Tests\Post::first();
        $this->assertEquals($post->title, $loadedPost->title);

        return $loadedPost;
    }

    /**
     * @test
     * @depends isDatabaseCreated
     * @dataProvider provider
     */
    public function canCreateAndHandleSimpleFormWithModelData($request, $needed, $record)
    {
        $form = EntryFormWithSaveOnHandle::create($record);
        $updated = $form->handle($request);
        $updated->save();

        $this->assertEquals($needed, $updated->title);
    }

    /**
     * @test
     * @depends isDatabaseCreated
     * @dataProvider provider
     */
    public function canCreateAndHandleFormWithModelDataAndSaveOnHandle($request, $needed, $record)
    {
        $form = EntryFormWithSaveOnHandle::create($record);
        $updated = $form->handle($request);

        $this->assertEquals($needed, $updated->title);
    }

    public function provider()
    {
        return [
            [ [ 'entry' => [ 'title' => 'Hello World!' ] ], 'Hello World!' ],
            [ [ 'entry' => [ 'title' => 1 ] ], 1 ],
            [ [ 'entry' => [ 'title' => null ] ], null ]
        ];
    }

}
